---
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: kedacore
  url: https://kedacore.github.io/charts
- name: local-path-provisioner
  url: git+https://github.com/rancher/local-path-provisioner@deploy/chart?ref=v0.0.25
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: cnpg
  url: https://cloudnative-pg.github.io/charts
- name: metrics-server
  url: https://kubernetes-sigs.github.io/metrics-server/
---
environments:
  default:
  dashboard:
---
releases:
{{ if false }}
- name: local-path-provisioner
  namespace: local-path-provisioner
  chart: local-path-provisioner/local-path-provisioner
  set:
  - name: storageClass.defaultClass
    value: true
{{ end }}
{{ range tuple "prom-system" "cnpg-system" }}
- name: {{ . }}-limitrange
  namespace: {{ . }}
  chart: ./limitrange
{{ end }}
- name: promstack
  namespace: prom-system
  chart: prometheus-community/kube-prometheus-stack
  version: 57.1.1
  values:
    - grafana:
        resources:
          requests:
            cpu: 0.1
            memory: 1G
          limits:
            cpu: 1
            memory: 1G
        {{ if .Environment.Name | eq "dashboard" }}
        {{- $pgusername := fetchSecretValue (printf "secretref+k8s://v1/Secret/app/db-app/username") }}
        {{- $pgpassword := fetchSecretValue (printf "secretref+k8s://v1/Secret/app/db-app/password") }}
        {{- $pghost     := printf "db-ro.app.svc.cluster.local" }}
        {{- $pgport     := "5432" }}
        {{- $pgdatabase := "messages" }}
        additionalDataSources:
          - name: cnpg
            type: postgres
            url: {{ $pghost }}:{{ $pgport }}
            user: {{ $pgusername }}
            secureJsonData:
              password: {{ $pgpassword }}
            jsonData:
              database: {{ $pgdatabase }}
              sslmode: 'disable'
              postgresVersion: 15 
        {{ end }}

    - prometheus:
        prometheusSpec:
          resources:
            requests:
              cpu: 100m # OpenAPI schema requires integer or string
              memory: 4G
            limits:
              cpu: 1
              memory: 4G
- name: keda
  namespace: keda-system
  chart: kedacore/keda
- name: rabbitmq
  namespace: rabbitmq-system
  chart: bitnami/rabbitmq-cluster-operator
- name: cnpg
  namespace: cnpg-system
  chart: cnpg/cloudnative-pg
{{ if false }}
- name: metrics-server
  namespace: kube-system
  chart: metrics-server/metrics-server
  values:
    - args: [ "--kubelet-insecure-tls" ]
{{ end }}
