{
 "title": "TravelGPT",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<img\n  \n  src=\"https://xavki.blog/wp-content/uploads/2024/03/enix-travel.png\"\n  alt=\"enix travel\" />\n"
   }
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"app\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"app\", workload_type=~\"deployment\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of pods",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"app\",container=~\"textsynth|benthos|rabbitmq|postgres\"})by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Rabbitmq - Ready messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info)"
    }
   ]
  },
  {
   "title": "Rabbitmq - Publishers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_global_publishers * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Rabbitmq - Consumers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_consumers * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info)"
    }
   ]
  },
  {
   "title": "Rabbitmq - Unacknowledged messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info)"
    }
   ]
  },
  {
   "title": "Rabbitmq - Incoming messages / s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_global_messages_received_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info)"
    }
   ]
  },
  {
   "title": "Rabbitmq - Outgoing messages / s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_global_messages_redelivered_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info) +\nsum(rate(rabbitmq_global_messages_delivered_consume_auto_ack_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info) +\nsum(rate(rabbitmq_global_messages_delivered_consume_manual_ack_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info) +\nsum(rate(rabbitmq_global_messages_delivered_get_auto_ack_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info) +\nsum(rate(rabbitmq_global_messages_delivered_get_manual_ack_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Database config - max connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_settings_setting{name=\"max_connections\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Database - Number connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 22 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (cnpg_backends_total)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "cnpg_pg_database_size_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database - Max Connections",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 22 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * sum by (pod) (cnpg_backends_total) / sum by (pod) (cnpg_pg_settings_setting{name=\"max_connections\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "TravelGPT", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "What can you visit ?",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT city, prompt, completion, submitted_at,generated_at FROM messages ORDER BY generated_at DESC LIMIT 50;"
    }
   ]
  }
 ]
}